// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7m8qq4qGdE8pZoLu5txqqDqVJDgXoxaw',
    appId: '1:962572529663:web:dc04c49ac8cadf4f84c1ca',
    messagingSenderId: '962572529663',
    projectId: 'eyz-movie',
    authDomain: 'eyz-movie.firebaseapp.com',
    storageBucket: 'eyz-movie.firebasestorage.app',
    measurementId: 'G-K7L927TRYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4_rdbYFlAL6ZfQRa7TdjOjpqVqmh76pc',
    appId: '1:962572529663:android:db9c486d3a474d3284c1ca',
    messagingSenderId: '962572529663',
    projectId: 'eyz-movie',
    storageBucket: 'eyz-movie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC122JI6I1lXAeQIkPL5vxIaoNe62-2EcI',
    appId: '1:962572529663:ios:2a0348235403ad1684c1ca',
    messagingSenderId: '962572529663',
    projectId: 'eyz-movie',
    storageBucket: 'eyz-movie.firebasestorage.app',
    androidClientId: '962572529663-9qgol30g8otiu3a0hfs1uput07j3nl7r.apps.googleusercontent.com',
    iosClientId: '962572529663-52s4gkqrutq6u6g5q7d52fv93h6tkn6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFilm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC122JI6I1lXAeQIkPL5vxIaoNe62-2EcI',
    appId: '1:962572529663:ios:2a0348235403ad1684c1ca',
    messagingSenderId: '962572529663',
    projectId: 'eyz-movie',
    storageBucket: 'eyz-movie.firebasestorage.app',
    androidClientId: '962572529663-9qgol30g8otiu3a0hfs1uput07j3nl7r.apps.googleusercontent.com',
    iosClientId: '962572529663-52s4gkqrutq6u6g5q7d52fv93h6tkn6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFilm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7m8qq4qGdE8pZoLu5txqqDqVJDgXoxaw',
    appId: '1:962572529663:web:b3c428ac411e13e384c1ca',
    messagingSenderId: '962572529663',
    projectId: 'eyz-movie',
    authDomain: 'eyz-movie.firebaseapp.com',
    storageBucket: 'eyz-movie.firebasestorage.app',
    measurementId: 'G-9PHDRRD51C',
  );

}